 #  try:
#     print('try')
# except:
#     print('except')
# finally:
#     print('finally')
# try:
#     print('try')
#     print(10/0)
# except ZeroDivisionError:
#     print('except')
# finally:
#     print('finally')
# try:
#     print('try')
#     print(10/0)
# except ValueError:
#     print('except')
# finally:
#     print('finally')
# import os
# try:
#     print('try')
#     os._exit(0)
# except ValueError:
#     print('except')
# finally:
#     print('finally')
#only os.exit(0) case finally block will not be executed.
# import os
# try:
#     print('try')
#     os._exit(0)
# except ValueError:
#     print('except')
# finally:
#     print('finally')









